### ISSUE TITLE
Wallpapers don't appear in the wallpaper APP.

### ISSUE THREAD

**Issue by XyasinX** [Magisk-Modules-Repo/pixel-complementary-live-wallpapers#1]
Wallpapers are not showing up in the app on my Pixel 2. Maybe bc the module only works with the April securitypatch?

**Comment by igor-dyatlov** [comment]
@XyasinX The module has a new installer. It downloads wallpapers from the cloud with the number of your security patch.

**Comment by luciodaou** [comment]
> 
> 
> @XyasinX The module has a new installer. It downloads wallpapers from the cloud with the number of your security patch.

I'm having the same problem. It says it's downloading, but that takes just a few seconds instead of minutes.

What I found out on my pixel 2: the date of August security patch is 2019-08-01, but your folders on gitlab are named 2019-08-05.

**Comment by luciodaou** [comment]
For the record, I solved that editing the install.sh and installing the module manually inside Magisk.
Steps:
1. Manual install fail as somehow the getprop doesn't work, so I edited line #136 to declare my Pixel 2 model name (walleye):
`DEVICE="walleye"` instead of https://github.com/Magisk-Modules-Repo/pixel-complementary-live-wallpapers/blob/48f2dd65a33ba07a66232d736b234cd96d47e2b2/install.sh#L136
2. August 2019 patch on my Pixel 2 is reported as 2019-08-01, but the GitLab folders are named 2019-08-05, so with a text editor, I replaced:
`raw/master/9/$SECURITY_PATCH_VERSION/`
with
`raw/master/9/2019-08-05/`
This way, the URLs are manually declared and it doesn't interfere with other functions of install.sh.

**Comment by igor-dyatlov** [comment]
@luciodaou This bug was fixed in the new version 2.1.1. Thank you for helping me find the bug. 
[magisk_install_log_2019-09-03T19:45:40Z.log](https://github.com/Magisk-Modules-Repo/pixel-complementary-live-wallpapers/files/3570534/magisk_install_log_2019-09-03T19.45.40Z.log)
