### ISSUE TITLE
device is system-as-root

### ISSUE THREAD

**Issue by r2binx** [Magisk-Modules-Repo/pixel-complementary-live-wallpapers#2]
Magisk fails to flash the zip file and says "device is system-as-root"
I tried it on the pixel 3a (june update) 

sorry if it's kind of an noob issue. It's my first a/b device and I dont really know how to flash on that without twrp

**Comment by igor-dyatlov** [comment]
@r2binx Try a new version of the module.

**Comment by luciodaou** [comment]
I have this issue on latest version when I install the module from the device (Modules section inside Magisk, then clicking the + button on bottom of the screen).

From the Downloads section, it works fine.

What I did to solve that was editing line #136 of install.sh and instead of the command, I declared the device name on double quotes.

So, for my Pixel 2:
`DEVICE="walleye"`

https://github.com/Magisk-Modules-Repo/pixel-complementary-live-wallpapers/blob/48f2dd65a33ba07a66232d736b234cd96d47e2b2/install.sh#L136
